version: "3"


services:
    backend:
        build: ./Backend-s
        
        depends_on:  
            - mongo
        environment:
            - PORT=9999
            - MONGODB_CNN=mongodb://mongo:27017/test
        
    fronted:
        build: ./Frontend-c
        
        depends_on:  
            - mongo
        environment:
            - PORT=4000
            - MONGODB_CNN=mongodb://mongo:27017/test 
    Microservicio:
        build: ./MicroServuce-Login

        depends_on:  
            - mongo
        environment:
            - PORT=5689
            - MONGODB_CNN=mongodb://mongo:27017/test 
        
        
    nginx:
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - backend
            - fronted
            - Microservicio
            
    mongo:
        image: mongo
        ports: 
            - "27017:27017"
        
            